source: dasmeta/modules/aws//modules/ingress
version: 2.14.7
variables:
  name: "demo-ingress"
  hostname: "boilerplate.yourdomain.com"
  additional_hostnames:
    - "*.boilerplate.yourdomain.com"
  # namespace: "dev"
  # scheme: "internal"
  certificate_arn: "${1-products/product-1/prod-1/certificate.arn}"
  healthcheck_path: "/health"
  healthcheck_success_codes: "200-399"
  tls_hosts:
    - "*.boilerplate.yourdomain.com"
  alarms:
    enabled: false
    sns_topic: ""
providers:
  - name: aws
    version: ~> 4.0
    module_nested_provider: true
    variables:
      default_tags:
        tags:
          Account: boilerplate
          ManageLevel: product
  - name: kubernetes
    version: ~> 2.23
    module_nested_provider: true
    source: "hashicorp/kubernetes"
    variables:
      cluster_ca_certificate: ${1-products/product-1/prod-1/certificate.arn}
      host: ${1-environments/prod-1/eks.cluster_host}
    blocks:
      exec:
        api_version: "client.authentication.k8s.io/v1beta1"
        args:
          - "eks"
          - "--region"
          - "eu-centeral-1"
          - "get-token"
          - "--cluster-name"
          - "demo-eks"
        command: "aws"
output:
  sensitive: true
linked_workspaces:
  - 1-environments/prod-1/eks
  - 1-products/product-1/prod-1/certificate