source: dasmeta/service/aws
version: 1.1.2
variables:
  name: "demo-service"
  cluster_name: "demo-eks"
  namespace: "service-namespace"
  create_namespace: true
  deploy_service: true
  alarms:
    sns_topic: "account-alarms-handling"
    maximum_replicas_usage:
      enabled: false
      maximum_replicas: 4
providers:
  - name: aws
    version: ~> 4.0
    module_nested_provider: true
    variables:
      region: eu-central-1
      access_key: <AWS-ACCESS-KEY>
      secret_key: <AWS-SECRET-KEY>
      default_tags:
        tags:
          Account: boilerplate
          ManageLevel: products
  - name: kubernetes
    version: ~> 2.23
    module_nested_provider: true
    source: "hashicorp/kubernetes"
    variables:
      cluster_ca_certificate: ${1-environments/prod-1/eks.cluster_certificate}
      host: ${1-environments/prod-1/eks.cluster_host}
    blocks:
      exec:
        api_version: "client.authentication.k8s.io/v1beta1"
        args:
          - "eks"
          - "--region"
          - "eu-central-1"
          - "get-token"
          - "--cluster-name"
          - "demo-eks"
        command: "aws"
  - name: helm
    version: "2.10.1"
    source: "hashicorp/helm"
    blocks:
      kubernetes:
        cluster_ca_certificate: ${1-environments/prod-1/eks.cluster_certificate}
        host: ${1-environments/prod-1/eks.cluster_host}
        blocks:
          exec:
            api_version: "client.authentication.k8s.io/v1beta1"
            args:
              - "eks"
              - "--region"
              - "eu-central-1"
              - "get-token"
              - "--cluster-name"
              - "demo-eks"
            command: "aws"
linked_workspaces:
  - 1-environments/prod-1/eks
